build:
	gcc -g -o program program.c
	./program Microsoft-Windows-DotNETRuntime:0xFFFFFFFFFFFFFFFF:1,Microsoft-Windows-DotNETRuntimePrivate:0xCAFEBABE:2
	./program Microsoft-Windows-DotNETRuntime:0xFFFFFFFFFFFFFFFF:1,Microsoft-Windows-DotNETRuntimePrivate:0xCAFEBABE,foo:0xdeadbeef
clean:
	rm program
